POST http://localhost:3001/api/locations
Content-Type: application/json
Authorization: Bearer JhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdXZlbGF6cXVlekBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjk1MTU3ODg3LCJleHAiOjE2OTUxNTc5NDd9.9CFZA79C3sxte-XnBCK74sTf3EAsp4aHHZErxbEMstk

{
  "lat": 8.29348, 
  "long": -6.334842,
  "locationName": "Parque Residencial Habitania",
  "locationAddress": "Parque Habitania, Ciudad Guayana 8050, Bolívar"
}