POST http://localhost:3001/api/user_accounts
Content-Type: application/json

{
  "firstName": "Mauricio",
  "lastName": "Velazquez",
  "email": "mauvelazquez@gmail.com",
  "password": "123456789",
  "roleId": "1"
}