POST http://localhost:3001/api/variables
Content-Type: application/json

{
    "variableType": "ENVIROMNTAL", 
    "variableName": "indice VOC",
    "variableUnit": "de 500"
}

//'ENVIROMENTAL', 'METEOROLOGICAL'